version: '3.8'

services:
  web-app:
    # The main user-facing web application.
    build: ./web-app
    container_name: web-app
    volumes:
      - ./web-app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mailhog

  mailhog:
    # Mail server for capturing and displaying emails sent by the application.
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Web interface for viewing emails.
      - "1025:1025" # SMTP port for sending emails.

  webmail-ui:
    # Webmail interface for users to view emails.
    image: php:8.1-apache
    container_name: webmail-ui
    volumes:
      - ./webmail-ui:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mailhog

  attacker-server:
    # Malicious server used to host and serve harmful links.
    build: ./attacker-server
    container_name: attacker-server
    ports:
      - "8082:80"